### ISSUE TITLE
Final Project Creating New Columns in the Data Set

### ISSUE THREAD

**Issue by jasminacosta** [Watts-College/paf-514-template#56] opened 2024-02-18 04:17 UTC
Hi @lecy!

I am still having issues with trying to make my function create a new column within my data set, and I tried creating the new column d$gender and reassigning the values inside of the vector "d$first.name" to the data set. 

I created the function and it is not outputting the new column when I run the function. 

```{r}

#PARSE FIRST NAME

get_first_name <- function( d )
{
  names <- strsplit( d$Full.Name, "," )
  first.name <- sapply( names, function(names){return(names[2])} )
  first.name <- trimws( first.name )
  first.name2 <- strsplit( first.name, " " )
  first.name2 <- sapply( first.name2, function(names){return(names[1])} )
  first.name2 <- trimws( first.name2 )
  
  d$first.name <- first.name2
  
  d <- first.name2
  
  return( d )
}

```

**Comment by jasminacosta** [comment] 2024-02-21 05:15
@lecy I chose to try out both solutions provided, and ultimately decided to add print statements to my function that way I can better see the results being printed. 

However, I am still having the issue with my function not adding the new column "d$first.name" despite adding print statements.

When I do run the function the results are all the first names within the data, but the new column is not being added.

```{r}

get_first_name <- function( d )
{
  names <- strsplit( d$Full.Name, "," )
  first.name <- sapply( names, function(names){return(names[2])} )
  first.name <- trimws( first.name )
  first.name2 <- strsplit( first.name, " " )
  first.name2 <- sapply( first.name2, function(names){return(names[1])} )
  first.name2 <- trimws( first.name2 )
  
  print( head( first.name2 ) ) 
  
  d$first.name <- first.name2
    print( head(d) )  
  
  d <- first.name2
    print( head(d) )  
  
  return( d )
}
get_first_name( d )

```

```{r}

[1] "Mohammad" "Jose"     "Kelsea"   "Enyah"    "Precious" "James"   

[1] "Mohammad" "Jose"     "Kelsea"   "Enyah"    "Precious" "James"   

   [1] "Mohammad"    "Jose"        "Kelsea"      "Enyah"       "Precious"   
   [6] "James"       "Morteza"     "Scott"       "Norma"       "Joshua"     
  [11] "Joshua"      "Amir"        "Olgeanna"    "Abdurazak"   "John"       
  [16] "Kelsey"      "James"       "Aditya"      "Karam"       "Millan"     
  [21] "Safaa"       "Naomi"       "Mykola"      "Cristen"     "Kristen"    
  [26] "Jay"         "Laura"       "Lauren"      "Mark"        "Deborah"    
  [31] "Francesco"   "Bessy"       "Lichelle"    "Anna"        "Talia"      
  [36] "Daniel"      "Gabriel"     "Jada"        "Abhinav"     "George"     
  [41] "Heather"     "Laura"       "Margaret"    "Martha"      "Antonio"    
  [46] "Ruben"       "Stephanie"   "Jennifer"    "Bradley"     "Elissa"     
  [51] "Allysa"      "Amy"         "Charity"     "Colton"      "Deborah"    
  [56] "Gary"        "James"       "Jennifer"    "Jill"        "Karen"      
  [61] "Marc"        "Mitchell"    "Raymond"     "Robert"      "Stephanie"  
  [66] "Tyler"       "Valerie"     "Lisa"        "Joni"        "Mark"       
  [71] "Marlin"      "Madelaine"   "Mary"        "Patricia"    "Ronald"     
  [76] "Angelica"    "Jacob"       "Sepideh"     "Timiebi"     "Scott"      
  [81] "Britta"      "Rimjhim"     "Alexandrina" "Iti"         "Akshay" etc....

```

**Comment by lecy** [comment] 2024-02-21 05:32
What is d at the start of the function?

I would need to see a preview of d before you call the function to be sure about what’s happening (fully reproducible example means I should be able to run the code you shared and get the same results). 

I know there’s definitely an issue with how you are assigning the names back to d but I’ll wait for the details of d.

**Comment by lecy** [comment] 2024-02-21 05:34
Good way to make the example reproducible:

```r
dput( head( d ) )
```

You can use a small slice of the data for a reproducible example.

**Comment by jasminacosta** [comment] 2024-02-21 05:54
@lecy 

D is my data and below is how I am loading it into R. 

```{r}

URL <- 'https://docs.google.com/spreadsheets/d/1RoiO9bfpbXowprWdZrgtYXG9_WuK3NFemwlvDGdym7E/export?gid=1335284952&format=csv'
d <- read.csv( URL )
head( d ) %>% pander()

```


```{r}

dput( head( d ) )

structure(list(Calendar.Year = c(2020L, 2020L, 2020L, 2020L, 
2020L, 2020L), Full.Name = c("ABBASI, Mohammad", "ARQUIZA, Jose Maria Reynaldo Apollo", 
"Aaberg, Kelsea", "Abadjivor, Enyah", "Abayesu, Precious", "Abbas, James"
), Job.Description = c("Research/Lab Assistant", "Lecturer", 
"Student Support Specialist", "Project Manager", "Management Intern", 
"Assoc Professor"), Department.Description = c("Sch Biological & Hlth Sys Engr", 
"Sch Biological & Hlth Sys Engr", "Admission Services", "CASGE  Tempe", 
"Health & Clinical Partnerships", "Sch Biological & Hlth Sys Engr"
), Salary = c("$35,090.00", "$71,400.00", "$36,000.00", "$64,000.00", 
"$20,800.00", "$107,195.00"), FTE = c(100L, 100L, 100L, 100L, 
50L, 100L)), row.names = c(NA, 6L), class = "data.frame")


```

**Comment by lecy** [comment] 2024-02-21 16:42
Are you seeing where it goes wrong? 

```r
d <- 
structure(list(Calendar.Year = c(2020L, 2020L, 2020L, 2020L, 
2020L, 2020L), Full.Name = c("ABBASI, Mohammad", "ARQUIZA, Jose Maria Reynaldo Apollo", 
"Aaberg, Kelsea", "Abadjivor, Enyah", "Abayesu, Precious", "Abbas, James"
), Job.Description = c("Research/Lab Assistant", "Lecturer", 
"Student Support Specialist", "Project Manager", "Management Intern", 
"Assoc Professor"), Department.Description = c("Sch Biological & Hlth Sys Engr", 
"Sch Biological & Hlth Sys Engr", "Admission Services", "CASGE  Tempe", 
"Health & Clinical Partnerships", "Sch Biological & Hlth Sys Engr"
), Salary = c("$35,090.00", "$71,400.00", "$36,000.00", "$64,000.00", 
"$20,800.00", "$107,195.00"), FTE = c(100L, 100L, 100L, 100L, 
50L, 100L)), row.names = c(NA, 6L), class = "data.frame")

d
  Calendar.Year                           Full.Name            Job.Description
1          2020                    ABBASI, Mohammad     Research/Lab Assistant
2          2020 ARQUIZA, Jose Maria Reynaldo Apollo                   Lecturer
3          2020                      Aaberg, Kelsea Student Support Specialist
4          2020                    Abadjivor, Enyah            Project Manager
5          2020                   Abayesu, Precious          Management Intern
6          2020                        Abbas, James            Assoc Professor
          Department.Description      Salary FTE
1 Sch Biological & Hlth Sys Engr  $35,090.00 100
2 Sch Biological & Hlth Sys Engr  $71,400.00 100
3             Admission Services  $36,000.00 100
4                   CASGE  Tempe  $64,000.00 100
5 Health & Clinical Partnerships  $20,800.00  50
6 Sch Biological & Hlth Sys Engr $107,195.00 100


names <- strsplit( d$Full.Name, "," )
first.name <- sapply( names, function(names){return(names[2])} )
first.name <- trimws( first.name )
first.name2 <- strsplit( first.name, " " )
first.name2 <- sapply( first.name2, function(names){return(names[1])} )
first.name2 <- trimws( first.name2 )
  
first.name2 
[1] "Mohammad" "Jose"     "Kelsea"   "Enyah"    "Precious" "James"   
 
d$first.name <- first.name2
d  
  Calendar.Year                           Full.Name            Job.Description
1          2020                    ABBASI, Mohammad     Research/Lab Assistant
2          2020 ARQUIZA, Jose Maria Reynaldo Apollo                   Lecturer
3          2020                      Aaberg, Kelsea Student Support Specialist
4          2020                    Abadjivor, Enyah            Project Manager
5          2020                   Abayesu, Precious          Management Intern
6          2020                        Abbas, James            Assoc Professor
          Department.Description      Salary FTE first.name
1 Sch Biological & Hlth Sys Engr  $35,090.00 100   Mohammad
2 Sch Biological & Hlth Sys Engr  $71,400.00 100       Jose
3             Admission Services  $36,000.00 100     Kelsea
4                   CASGE  Tempe  $64,000.00 100      Enyah
5 Health & Clinical Partnerships  $20,800.00  50   Precious
6 Sch Biological & Hlth Sys Engr $107,195.00 100      James
   
d <- first.name2
d  
[1] "Mohammad" "Jose"     "Kelsea"   "Enyah"    "Precious" "James"   
```

The print output above did not match the output here, which is why I was wondering if your data frame might have been corrupted before it got to this step. It's easier to see with a reproducible example.

**Comment by jasminacosta** [comment] 2024-02-22 01:05
@lecy I am not quite understanding or seeing the different outputs.

**Comment by lecy** [comment] 2024-02-22 08:02
You make two assignments to d. What type of object is d after the first. And what type of object after the second?

```r
d$first.name <- first.name2
d  
  Calendar.Year                           Full.Name            Job.Description
1          2020                    ABBASI, Mohammad     Research/Lab Assistant
2          2020 ARQUIZA, Jose Maria Reynaldo Apollo                   Lecturer
3          2020                      Aaberg, Kelsea Student Support Specialist
4          2020                    Abadjivor, Enyah            Project Manager
5          2020                   Abayesu, Precious          Management Intern
6          2020                        Abbas, James            Assoc Professor
          Department.Description      Salary FTE first.name
1 Sch Biological & Hlth Sys Engr  $35,090.00 100   Mohammad
2 Sch Biological & Hlth Sys Engr  $71,400.00 100       Jose
3             Admission Services  $36,000.00 100     Kelsea
4                   CASGE  Tempe  $64,000.00 100      Enyah
5 Health & Clinical Partnerships  $20,800.00  50   Precious
6 Sch Biological & Hlth Sys Engr $107,195.00 100      James
   
d <- first.name2
d  
[1] "Mohammad" "Jose"     "Kelsea"   "Enyah"    "Precious" "James"   
`’``

**Comment by jasminacosta** [comment] 2024-02-22 16:14
@lecy 

The first assignment makes the columns and the output is a date frame with the first 6 people and their information from the data set. 

```{r}

d$first.name <- first.name2
d  

```

<img width="580" alt="Screenshot 2024-02-22 at 8 07 25 AM" src="https://github.com/Watts-College/paf-514-template/assets/136217967/a83c289d-06af-445a-9e74-1a566c327d85">

While the second assignment only provides the first names and does not create the new column. 

My confusion is when I run the function as the first example:

```{r}

get_first_name <- function( d )
{
  names <- strsplit( d$Full.Name, "," )
  first.name <- sapply( names, function(names){return(names[2])} )
  first.name <- trimws( first.name )
  first.name2 <- strsplit( first.name, " " )
  first.name2 <- sapply( first.name2, function(names){return(names[1])} )
  first.name2 <- trimws( first.name2 )
  
  print( head( first.name2 ) ) 
  
  d$first.name <- first.name2
    print( head(d) )  
  
  d 
  
  return( d )
}
get_first_name( d )

```

I do not see the new column added to the actual data set, but the new column is added to a data frame when the function is ran. 

In data "d" it still has the same number of variables which is 6, as opposed to 7 when we need to add the first name column.

**Comment by lecy** [comment] 2024-02-22 17:27
The function produces the correct result, but you still need to assign it, otherwise you are just printing the results by executing the function.

```r
d <- get_first_name( d )
```

**Comment by jasminacosta** [comment] 2024-02-22 17:30
@lecy Got it, and when we put our functions into the utilities file we can include that assignment as well, correct? Or would it impact the utilities file?

**Comment by lecy** [comment] 2024-02-22 19:19
When you source a file, similar to knitting an RMD, you run it from top to bottom in a fresh R environment. What I mean by fresh R environment is that even if you have loaded data in your console, when you knit the RMD it will not be able to access that data unless you explicitly load it in the RMD file because a fresh R environment is an empty environment.  

What would happen if you added that last data assignment step in your utilities file and then ran it? Specifically, what data frame **d** would the line have access to? 

Where does get_first_name() fit in your current workflow?

**Comment by jasminacosta** [comment] 2024-02-22 19:35
@lecy For the get_first_name() function right now in my RMD it is my step after I load the data, but to put it in the utilities file it would be the first function within that file because we need that function to then continue on adding the gender within the data based on the first name. 

What would happen if you added that last data assignment step in your utilities file and then ran it? Specifically, what data frame d would the line have access to? <- It would have access to the d data set and the first name of the person within the data?

**Comment by lecy** [comment] 2024-02-22 22:25
Correct, if you add this line to your utils.R file: 

```r
d <- get_first_name( d )
```

Then you would also need to load data inside of the utils file in order to not produce an error when you source the file because the dataset does not yet exist. That means you now have to data workflows - the explicit one in your analytics file: 

```r
d <- read.csv( ... )

d %>%
  # data prep functions %>%
  create_salary_table() %>%   
  build_graph( unit = "Psych" )
```


And also one inside of your utilities file. If you load the data in two places you may be overwriting an existing dataset, thus producing errors or unexpected results. 

From a project management perspective, you want to minimize complexity by separating the functions from the workflow script (your data recipe). Ideally you should be able to look at the recipe and see clearly how the data flows through the process: 

It's predictable if the functions are the only thing changing your data. If you start adding data steps to external scripts then it becomes much more nebulous. I know how the data is changing if I can see all of the functions in the workflow and I have their documentation. Functions are input-output machines, and the documentation should say how the output differs from the input. 

If you include data steps in scripts that you are sourcing it is not as obvious. We would have to look inside the scripts for more details. 

```r
d <- read.csv( URL )

source( "utils.R" )

d <- 
  d %>% 
  get_first_name()
  add_gender()

source( "script.R" )

d <- 
  d %>%
  add_titles()
  fix_salary()
```

Your project will be easier to manage if the steps in your workflow are more explicit and transparent - it can be easily understood by looking at the data recipe sections of the file: 

![image](https://github.com/Watts-College/paf-514-template/assets/1209099/1708c623-52ee-4a6c-92ee-31ed71dd0907)

This is why you see projects like the data driven resume moving all of the code that creates the functions to an external utilities R file, and only manipulating the data inside of the RMD template file. 

https://watts-college.github.io/paf-514-template/lectures/report-automation.html

**Comment by jasminacosta** [comment] 2024-02-23 03:49
@lecy That makes sense especially since for the function-demo.rmd and salary-report.rmd we are loading the data differently.

In that case when we put our functions into the utilities file, do we remove the line of code where we create a new column for our data set?

Because if we do that wouldn't it mess with the data workflow since the new columns are not there in the data set?

**Comment by lecy** [comment] 2024-02-23 16:37
You confirmed above, the function returns a data frame with the new columns added. 

You just need to utilize assignment in your report (I'm using numbers here for clarity, but not needed): 

```r
d1 <- read.csv()
d2 <- get_first_name( d1 )
```

You might be confusing yourself because some steps of the workflow do not require saving the data. You might just call it for the side effects: 

```r
d <- 
  create_summary_table() %>% 
  build_graph()
```

In cases where you do need to preserve the steps (in the data wrangling stages, for example), you can always add assignment to the piped operators: 

```r
d <- 
  d %>%  
  get_first_name() %>% 
  add_gender()
```

OR: 

```r
 d %>%  
  get_first_name() %>% 
  add_gender() -> d
```

**Comment by jasminacosta** [comment] 2024-02-23 20:08
@lecy Got it, that makes a lot more sense! 

Thank you for the clarity 😁

**Closed** 2024-08-20 22:00 UTC
Labels: FINAL_PROJECT
